amazing/config/routes.rb
Rails.application.routes.draw do
  resources :books do
    get :search, :on => :collection
  end

  resources :handlers, :only => [:index]

  root 'books#index'
end

amazing/app/models/book.rb
class Book < ActiveRecord::Base
  def self.search(term)
    where('LOWER(title) LIKE :term OR LOWER(author) LIKE :term', term: "%#{term.downcase}%")
  end
end

amazing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

amazing/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.order(:title).limit(50)
  end

  def search
    respond_to do |format|
      format.html
      format.json { @books = Book.search(params[:term]) }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :price, :published_at)
    end
end

amazing/app/controllers/handlers_controller.rb
class HandlersController < ApplicationController
  def index
    @books = []
    @books << Book.new(title: 'Da Vinci Code', author: 'Dan Brown')
    @books << Book.new(title: 'Name of the Rose', author: 'Umberto Eco')
  end
end

amazing/app/helpers/application_helper.rb
module ApplicationHelper
  def page_class
    "page-#{controller_name} #{action_name.gsub(/-/, '_')}"
  end
end

amazing/app/helpers/books_helper.rb
module BooksHelper
end

amazing/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

amazing/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

amazing/app/views/books/index.html.erb
<article class="app-cont books-list">

  <section class="app-title cf">
    <h1>Books</h1>
    <%= link_to 'New Book', new_book_path %>
    <%= link_to 'Download (CSV)', books_path(:format => :csv) %>
  </section>

  <section class="app-content">
    <% @books.each do |book| %>
      <div class="book">
        <p class="img">
          <%= image_tag book.image_url %>
        </p>
        <h3 class="title"><%= book.title %></h3>
        <h4 class="author">by <%= book.author %></h4>
        <p class="details">
          <span><%= number_to_currency(book.price) %></span>
          <span>Published on <%= book.published_at.strftime('%B %Y') %></span>
        </p>
      </div>
    <% end %>
  </section>

</article>

amazing/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

amazing/app/views/books/search.html.erb
<article class="app-cont">

  <section class="app-title cf">
    <h1>Books</h1>
    <%= link_to 'New Book', new_book_path %>
  </section>

  <section class="app-content">
    <div class="books-search">
      <input type="text" id="books-search-txt" autofocus>
      <div class="results" id="books-search-results"></div>
    </div>
  </section>

</article>

<%= content_for :script do %>
  new app.Books;
<% end %>

amazing/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @book.published_at %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

amazing/app/views/layouts/_header.html.erb
<header class="app-header">
  <div class="inner app-cont cf">
    <h1 class="logo">
      <%= link_to 'amazing books', root_path %>
    </h1>

    <nav class="nav">
      <li><%= link_to 'Search', search_books_path %></li>
    </nav>
  </div>
</header>

amazing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amazing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= page_class %>">

<%= render 'layouts/header' %>
<%= yield %>

<script>
  $(function() {
    <%= yield :script %>
  });
</script>

</body>
</html>